buildscript {
    ext.rxJavaVersion = '2.2.17'
}

plugins {
    id 'java-library'
    id 'org.jetbrains.kotlin.jvm'
    id 'com.google.devtools.ksp'
    id 'com.google.protobuf' version '0.10.0'
}

def protobuf_version = "4.30.2"



protobuf {

    protoc {
        artifact = "com.google.protobuf:protoc:$protobuf_version"
    }
    generateProtoTasks {
        all().each { task ->
            task.builtins {
                java {
                    // turned off for now so I can use json printing in debug panel
                    // use the smaller android version of the library
                    //option "lite"
                }
                kotlin {
                }
            }
        }
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
    sourceSets {
        main {
            proto.srcDirs = ["src/main/proto", "src/main/meshtastic"]
        }
    }
}

dependencies {
    implementation("com.google.protobuf:protobuf-kotlin:$protobuf_version")
    implementation "io.reactivex.rxjava2:rxjava:$rxJavaVersion"
    implementation "com.google.protobuf:protobuf-kotlin:$protobuf_version"
    implementation libs.rxjava2.extras
}

repositories {
    mavenCentral()
    google()
    maven { url "https://jitpack.io" }
    gradlePluginPortal()
}