language: android
dist: trusty
sudo: required
jdk: openjdk11
env:
  global:
    - TARGET_VERSION=32
    - ANDROID_BUILD_TOOLS_VERSION=30.0.3
    - ANDROID_HOME=~/android-sdk
    - ANDROID_SDK_ROOT=$ANDROID_HOME
android: 
   components:
      - tools
      - platform-tools
      - extra-android-m2repository
before_install:
  - touch $HOME/.android/repositories.cfg
  - wget "https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip" -O commandlinetools.zip
  - unzip commandlinetools.zip -d $ANDROID_HOME/
  - chmod +x gradlew
  - yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager "platforms;android-${TARGET_VERSION}" --sdk_root=$ANDROID_HOME
  - yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager "build-tools;${ANDROID_BUILD_TOOLS_VERSION}" --sdk_root=$ANDROID_HOME

script:
  - ./gradlew build testDebugUnitTest jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash) 


