plugins {
    id 'com.android.library'
    id 'kotlin-android'
    id 'com.google.devtools.ksp'
    id("org.jetbrains.kotlin.plugin.parcelize")
    id("org.jetbrains.dokka") version "1.8.20"
}


android {
    defaultConfig {
        minSdkVersion 26
        targetSdkVersion 36
        compileSdkVersion 36
        multiDexEnabled true
        javaCompileOptions {
            annotationProcessorOptions {
                arguments += [
                        "room.incremental": "true",
                        "room.schemaLocation": "$projectDir/schemas".toString()
                ]
            }
        }
        ksp {
            arg("room.incremental", "true")
            arg("room.schemaLocation", "$projectDir/schemas")
        }

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

    }

    buildTypes {
        release {
            minifyEnabled false
            //proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            minifyEnabled false
        }
    }

    namespace 'net.ballmerlabs.uscatterbrain'

    testOptions {
        unitTests {
            includeAndroidResources = true
        }
    }
    packagingOptions {
        resources {
            pickFirsts += ['META-INF/com.google.dagger_dagger.version']
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }

    java {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
    }

    buildFeatures {
        aidl true
    }

    sourceSets{
        androidTest.assets.srcDirs += files("$projectDir/schemas".toString())
    }

    useLibrary 'android.test.base'
    useLibrary 'android.test.mock'
    lint {
        abortOnError false
        disable 'JvmStaticProvidesInObjectDetector', 'FieldSiteTargetOnQualifierAnnotation', 'ModuleCompanionObjects', 'ModuleCompanionObjectsNotInModuleParent'
    }
    namespace 'net.ballmerlabs.uscatterbrain'
}

apply from: "../scatterbrainSDK/gradle/jacoco.gradle"

def protobuf_version = "4.30.2"
/*
configurations {
    configureEach {
        resolutionStrategy {
            force "com.goterl:lazysodium-android:5.1.0@aar"
            force "net.java.dev.jna:jna:5.12.1@aar"
        }
    }
}

 */

dependencies {
    def lifecycle_version = "2.8.2"
    def dagger_version = "2.55"
    implementation libs.appcompat
    implementation libs.protobuf.kotlin
    implementation libs.protobuf.kotlin
    implementation libs.room.runtime

    implementation(libs.androidx.security.crypto)

    implementation libs.rxjava2.debug

    //reflect for logging
    implementation libs.kotlin.reflect

    // websockets
    implementation libs.ktor.server.websockets

    implementation project(':scatterbrainSDK')
    androidTestImplementation project(':scatterbrainSDK')
    implementation libs.rxrelay
    implementation libs.rxdogtag
    implementation libs.rxandroidble
    implementation libs.kotlinx.collections.immutable.v037

    testImplementation libs.mockclient
    androidTestImplementation libs.mockclient

    ksp libs.room.compiler // For Kotlin use kapt instead of annotationProcessor
    implementation libs.androidx.lifecycle.service
    androidTestImplementation libs.androidx.espresso.idling.resource
    androidTestImplementation libs.androidx.runner
    androidTestImplementation libs.androidx.rules
    // Optional -- Hamcrest library
    androidTestImplementation 'org.hamcrest:hamcrest-library:1.3'
    // Optional -- UI testing with Espresso
    androidTestImplementation libs.espresso.core
    // Optional -- UI testing with UI Automator
    androidTestImplementation libs.androidx.uiautomator
    androidTestImplementation libs.room.testing

//    //lazysodium cryptographic library
//    implementation(libs.lazysodium.android)
//    implementation libs.jna
    implementation "com.goterl:lazysodium-android:5.2.0@aar"
    implementation "net.java.dev.jna:jna:5.17.0@aar"
    implementation libs.androidx.datastore.preferences
    implementation libs.androidx.datastore.preferences.rxjava2


    //lazysodium cryptographic library
    testImplementation "com.goterl:lazysodium-android:5.2.0@aar"
    testImplementation 'net.java.dev.jna:jna:5.17.0@aar'
    testImplementation 'net.java.dev.jna:jna-platform:5.17.0'

    implementation libs.rxjava2.extras.v022

    implementation libs.dagger
    testImplementation libs.dagger
    implementation libs.dagger.android
    implementation libs.dagger.android.support

    ksp "com.google.dagger:dagger-android-processor:$dagger_version"
    ksp "com.google.dagger:dagger-compiler:$dagger_version"
    kspTest "com.google.dagger:dagger-compiler:$dagger_version"


    implementation libs.rxjava

    implementation libs.rxandroid

    implementation libs.androidx.room.rxjava2

    implementation libs.rxjava2.extras
    testImplementation libs.rxjava

    testImplementation libs.rxandroid

    testImplementation libs.androidx.room.rxjava2

    testImplementation libs.rxjava2.extras

    implementation libs.core.ktx
    androidTestImplementation libs.androidx.core
    implementation libs.kotlin.stdlib.jdk7
    implementation libs.google.firebase.crashlytics
    androidTestImplementation libs.google.firebase.crashlytics
    implementation libs.jetbrains.kotlinx.coroutines.core
    // Required -- JUnit 4 framework
    testImplementation libs.junit
    // Optional -- Robolectric environment
    testImplementation libs.androidx.core
    implementation libs.sqlite.android
    androidTestImplementation libs.sqlite.android
    testImplementation libs.sqlite.android
    testImplementation libs.robolectric
    // Optional -- Mockito framework
    testImplementation libs.mockito.core
    // Optional -- mockito-kotlin
    testImplementation libs.mockito.kotlin

    // Optional -- Mockito framework
    implementation libs.mockito.core
    // Optional -- mockito-kotlin
    implementation libs.mockito.kotlin

    // Optional -- Mockito framework
    androidTestImplementation libs.mockito.core
    // Optional -- mockito-kotlin
    androidTestImplementation libs.mockito.kotlin
    // Optional -- Mockk framework
    testImplementation libs.mockk
    testImplementation libs.androidx.monitor
    testImplementation libs.androidx.core.ktx
    testImplementation libs.androidx.core
    androidTestImplementation libs.junit
    def work_version = "2.10.0"

    // (Java only)
    implementation(libs.androidx.work.runtime)

    // Kotlin + coroutines
    implementation(libs.androidx.work.runtime.ktx.v2100)

    // optional - RxJava2 support
    implementation(libs.androidx.work.rxjava2)

    // optional - GCMNetworkManager support
    implementation(libs.androidx.work.gcm)

    // optional - Test helpers
    androidTestImplementation(libs.androidx.work.testing)

    // optional - Multiprocess support
    implementation libs.androidx.work.multiprocess

    implementation libs.kotlinx.coroutines.rx2
    implementation libs.rxjava2.extras
    implementation(project(':annotation'))
    ksp(project(':annotation'))
    implementation(project(':ser'))
}
repositories {
    google()
    mavenCentral()
    gradlePluginPortal()
    maven { url "https://jitpack.io" }
}
